version: "3"

services:
  app:
    image: ghcr.io/jhon-acosta/signed.chat:latest
    ports:
      - 3000:3000
      - 3001:3001
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      TZ: America/Guayaquil
      NODE_ENV: production
